ALTER TABLE tenants ADD COLUMN IF NOT EXISTS profile VARCHAR(50) NOT NULL DEFAULT 'SINGLE_SITE';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS hidden_modules TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS show_advanced_fields BOOLEAN NOT NULL DEFAULT false;
