ALTER TABLE devices ADD COLUMN IF NOT EXISTS management_ip VARCHAR(255);
ALTER TABLE devices ADD COLUMN IF NOT EXISTS mac_address VARCHAR(17);
ALTER TABLE devices DROP CONSTRAINT IF EXISTS check_rack_or_site;
